baseURL: "https://marcel.works"
title: marcel.works
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: marcel.works
  description: "technological non sense"
  author: Marcel
  images: [ "<link or path of image for opengraph, twitter-cards>" ]

  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  disableSpecial1stPost: false
  comments: false
  hidemeta: false
  showtoc: false
  tocopen: false

  assets:
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  cover:
    hidden: false
    hiddenInList: false
    hiddenInSingle: false

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content" ]

menu:
  main:
    - identifier: posts
      name: posts
      url: /post/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20